#!/bin/sh
. /www/usr-cgi/inicioLigero.sh

echo '<table class="estr">'

echo '<tr>'
echo '<h3>Orden Telemando Tomar Muestra</h3>'
echo '<br>'
echo '<form action=ordentelemandoDig.sh method=POST>'
echo '<table class="cent" border=0>'
echo '<tr><td>Se&ntilde;al</td><td>'
echo '<select name="sen">'
echo '<option value="10">TOMAR MUESTRA</option>'
#echo '<option value="2">2</option>'
#echo '<option value="3">3</option>'
#echo '<option value="4">4</option>'
echo '</select>'
echo '</td>'
#echo '<td>Activar/Desactivar</td><td>'
echo '<td><select name="activar">'
echo '<option value="1">Activar (1)</option>'
echo '<option value="0">Desactivar (0)</option>'
echo '</select>'
echo '</td>'
echo '<td></td><td><input class="boton" type=submit value="Orden Telemando"></td></tr>'
echo '</table>'
echo '</form>'
echo '<br>'
echo '</tr>'

echo '<tr>'
echo '<h3>Orden Telemando Control Caudal</h3>'
echo '<br>'
echo '<form action=ordentelemandoServo.sh method=POST>'
echo '<table class="cent" border=0>'
echo '<tr><td>Se&ntilde;al</td><td>'
echo '<select name="sen">'
echo '<option value="9">Caudal</option>'
#echo '<option value="2">2</option>'
#echo '<option value="3">3</option>'
#echo '<option value="4">4</option>'
echo '</select>'
echo '</td>'
#echo '<td>Activar/Desactivar</td><td>'
echo '<td><select name="activar">'
echo '<option value="0">0</option>'
echo '<option value="45">45</option>'
echo '<option value="90">90</option>'
echo '<option value="135">135</option>'
echo '<option value="180">180</option>'
echo '</select>'
echo '</td>'
echo '<td></td><td><input class="boton" type=submit value="Orden Telemando"></td></tr>'
echo '</table>'
echo '</form>'
echo '<br>'
echo '</tr>'


echo '</table>'

/www/usr-cgi/fin.sh /usr-cgi/inicioLigero.sh
